service: hms-email-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: email/send
          method: post
